### ISSUE TITLE
"lottblocks:banner_top" has no recipe

### ISSUE THREAD

**Issue by mgl512** [minetest-LOTR/Lord-of-the-Test#101]
It's the required craftitem shared between the various (awesome) banners/tapestries. Didn't find any in chests either. So it's impossible to craft the banners.

**Comment by Amaz1** [comment]
Fixed, thanks!
https://github.com/minetest-LOTR/Lord-of-the-Test/commit/ea3df02732e7feea85cf1d11124bb72984fd3e22
