### ISSUE TITLE
Quests, lore, etc. are lacking.

### ISSUE THREAD

**Issue by Xaleth** [minetest-LOTR/Lord-of-the-Test#118]
If you've read the LOTR volumes, then you could tell that lore played a huge role.

But I barely see anything in this subgame, other than the guides. I did try to help by adding a lot of sayings to the dwarves and elves.

Maybe add scrolls that randomly spawn in generated chests that contain lore.

Add quests?

I can help with this aspect of the subgame.

**Comment by Amaz1** [comment]
Yeah, this is something that really needs to be done...
Quests would be very good as well.
Both of these things would benefit greatly from the "proper" mapgen I'm working on... Yet another reason to do more work on it, I suppose :P

**Comment by Amaz1** [comment]
Something for the rewrite, will be looked at then.
