### ISSUE TITLE
Help on guide_on_use

### ISSUE THREAD

**Issue by NewbProgrammer101** [minetest-LOTR/Lord-of-the-Test#119]
I am creating the first scroll for LOTT and I have this in the guides.lua:

local lore_poem1 = dofile(minetest.get_modpath("lottblocks")
        .. "/guide_text/lore_poem1.lua")

minetest.register_craftitem("lottblocks:lore_scroll1", {
        description = "Scroll labeled A GILTHONIEL",
        inventory_image = "scroll.png",
        groups = {book = 1, forbidden = 1},
        stack_max = 1,
        text = minetest.deserialize(lore_poem1),
        on_use = function(itemstack, user)
                 guide_on_use(itemstack, user)
        end,
})

and the map loaded without any errors; however, when I left-click on the scroll, the map crashes and returns:

`2017-10-22 13:00:59: ACTION[Server]: singleplayer uses lottblocks:lore_scroll1, pointing at [node
under=-134,14,-126 above=-134,15,-126]

2017-10-22 13:00:59: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'lottblocks' in callback item_OnUse(): ...st/games/Lord-of-the-Test/mods/lottblocks/guides.lua:9: attempt to index local 'data' (a nil value)

2017-10-22 13:00:59: ERROR[Main]: stack traceback:

2017-10-22 13:00:59: ERROR[Main]: 	...st/games/Lord-of-the-Test/mods/lottblocks/guides.lua:9: in function 'guide_on_use'

2017-10-22 13:00:59: ERROR[Main]: 	...st/games/Lord-of-the-Test/mods/lottblocks/guides.lua:98: in function <...st/games/Lord-of-the-Test/mods/lottblocks/guides.lua:97>
`
I really don't know how the Palantir guide works even with the exact setup as the lore_scroll.

Help.

**Comment by NewbProgrammer101** [comment]
`return "return{{\"background\"} = \"gui_elfbg.png\", " ..
	"{\"page\"} = 1, [\"title\" = \"A GILTHONIEL\", " ..
	"[\"page_max\"] = 15, [\"text_len\"] = 2640, [\"owner\"] = \"Gildor Inglorion\", " ..
	"[\"text\"] = \"Snow-white! Snow-white! O lady clear! " ..
	"\\\nQueen beyond the Western Sea! " ..
	"\\\nO Light to us that wander here " ..
	"\\\nAmid the world of woven trees! " ..
	"\\\n\\\nGilthoniel! O Elbereth! " ..
	"\\\nClear are thy eyes and bright thy breath. " ..
	"\\\nSnow-white! Snow-white! We sing to thee " ..
	"\\\nIn a far land beyond the Sea. " ..
	"\\\n\\\nO stars that in the Sunless Year " ..
	"\\\nWith shining hand by her were sown, " ..
	"\\\nIn windy fields now bright and clear " ..
	"\\\nWe see your silver blossom blown. " ..
	"\\\n\\\nO Elbereth! Gilthoniel! " ..
	"\\\nWe still remember, we who dwell " ..
	"\\\nIn this far land beneath the trees, " ..
	"\\\nThy starlight on the Western Seas. " ..
	"\\\n\\\nA Elbereth Gilthoniel, " ..
	"\\\nSilivren penna miriel " ..
	"\\\nO menal aglar elenath! " ..
	"\\\nNa-chaered palan-diriel " ..
	"\\\nO galadhremmin ennorath, " ..
	"\\\nFanuilos, le linnathon " ..
	"\\\nnef aear, si nef aearon! " ..
	"\\\n\\\nAi! laurie lantar lassi surinen! " ..
	"\\\nYeni unotime ve ramar aldaron, " ..
	"\\\nYeni ve linte yuldar vanier " ..
	"\\\nMi oromardi lisse-miruvoreva " ..
	"\\\nAndune pella Vardo tellumar " ..
	"\\\nNu luini yassen tintilar i eleni " ..
	"\\\nOmaryo airetari-lirinen. " ..
	"\\\n\\\nSi man i yulma nin enquantuva? " ..
	"\\\n\\\nAn si Tintalle Varda Oilosseo " ..
	"\\\nVe fanyar maryat Elentari ortane, " ..
	"\\\nAr ilye tier undulare lumbule; " ..
	"\\\nAr sindanoriello caita mornie " ..
	"\\\nI falmalinnar imbe met, ar hisie " ..
	"\\\nUntupa Calaciryo miri oiale. " ..
	"\\\nSi vanwa na, Romello vanwa, Valimar! " ..
	"\\\nNamarie! Nai hiruvalye Valimar. " ..
	"\\\nNai elye hiruva. Namarie! " ..
	"\\\n\\\nAh! Like gold fall the leaves in the wind, " ..
	"\\\nLong years numberless as the wings of trees! " ..
	"\\\nThe long years have passed like swift draughts of the sweet mead " ..
	"\\\nIn lofty halls beyond the West " ..
	"\\\nBeneath the blue vaults of Varda " ..
	"\\\nWherein the stars tremble in the song of her voice, " ..
	"\\\nHoly and queenly. " ..
	"\\\n\\\nWho now shall refill the cup for me? " ..
	"\\\nFor now the Kindler, Varda, " ..
	"\\\nThe Queen of the Stars, from Mount Everwhite " ..
	"\\\nHas uplifted her hands like clouds, " ..
	"\\\nAnd all paths are drowned deep in shadow; " ..
	"\\\nAnd out of a grey country darkness lies on the foaming waves between us, " ..
	"\\\nAnd mist covers the jewels of Calacirya for ever. " ..
	"\\\nNow lost, lost to those from the East is Valimar! " ..
	"\\\n\\\nFarewell! Maybe thou shalt find Valimar. " ..
	"\\\nMaybe even thou shalt find it! Farewell! " ..
	"\\\n\\\nGilthoniel A Elbereth! " ..
	"\\\nA Elbereth Gilthoniel " ..
	"\\\nO menel palan-diriel, " ..
	"\\\nLe nallon si dinguruthos! " ..
	"\\\nA tiro nin, Fanuilos! " ..
	"\\\n\\\nA! Elbereth Gilthoniel! " ..
	"\\\nSilivren penna miriel " ..
	"\\\nO menal aglar elenath, " ..
	"\\\nGilthoniel, A! Elbereth! " ..
	"\\\nWe still remember, we who dwell " ..
	"\\\nIn this far land beneath the trees " ..
	"\\\nThy starlight on the Western Seas.\"}"
`

This is lore_poem1.lua

**Comment by Amaz1** [comment]
You need to make sure that the file that the guide is saved in has a specific format.
It should be something along the lines of the following:
```lua
return "return {[\"background\"] = \"gui_rohanbg.png\"," ..
	"[\"title\"] = \"Concerning the Rings of Power\", [\"page_max\"] = 19," ..
	"[\"text_len\"] = 8622, [\"owner\"] = \"Author\", [\"text\"] = \blah blah blah\"}"
```

The reason it uses this ridiculous format is because I based the guides on written books, as that was the best way of dealing with long texts in a formspec. However, since https://github.com/minetest/minetest/commit/e6e5fa3bf8853f149fdef16b39af3981097176a4, readonly textareas are a better way of doing this (much, much simpler. Books should probably be converted to using them as well...). I'll probably do this at some point.

**Comment by NewbProgrammer101** [comment]
Hm, strange...
I followed your steps on the format, but I'm still getting the same errors as the original post.

**Comment by NewbProgrammer101** [comment]
EDIT: Fixed now.

Forgot to replace the braces for \"background\" with brackets.

Thank you.
