### ISSUE TITLE
Overgeneration of structures.

### ISSUE THREAD

**Issue by Xaleth** [minetest-LOTR/Lord-of-the-Test#123]
The structures are generated too much. i.e. When you enter the Mordor biome, you see the dark tower everywhere, some towers even overlap each other. The same goes with every other biome.

The structures should be a lot rarer.

**Comment by fishyWET** [comment]
The current issue is that there's really no proper spawning system in place, structures are placed randomly.
Definitely a todo.

**Comment by Amaz1** [comment]
Will be sorted in v2.
If still an issue then, this can be reopened!
