### ISSUE TITLE
Crash after "grant singleplayer all"

### ISSUE THREAD

**Issue by trungus** [minetest-LOTR/Lord-of-the-Test#130]
Hi there,

I have a problem, I have a recent compiled source (lastet source available in github) and when I open a world (by create or load) and run the command "/grant singleplayer all" the game crash.

Some Idea?.

PS: I try with version 1.1.0 and lastet master version, same result in both cases.

[debug.txt](https://github.com/minetest-LOTR/Lord-of-the-Test/files/1934868/debug.txt)

**Comment by Amaz1** [comment]
minetest.auth_table seems to have been removed, and replaced with minetest.player_exists. Should hopefully fix your crash!
