### ISSUE TITLE
Problem running v1.1.0

### ISSUE THREAD

**Issue by b3u** [minetest-LOTR/Lord-of-the-Test#131]
Game doesn't run when I downloaded it and placed it in the C:\Minetest/Lord-of-the-Test-Master.
It says: "ModError: Failed to load and run C:\Minetest\..\games\Lord-of-the-Test-Master\mods\default\init.lua". Error is shown below. I tried replacing the file init.lua with minecraft-game's file, but it didn't help. Game looks good, though!
![image](https://user-images.githubusercontent.com/39805353/41671680-d3a4c358-7485-11e8-8a6d-31e4daf0ce1b.png)

**Comment by Amaz1** [comment]
What version of Minetest are you using?
And could you paste the last 15 lines of the debug.txt file after a crash?

**Comment by neinwhal** [comment]
It sounds more like a faulty download. Can you delete the entire folder and redownload it?

**Comment by b3u** [comment]
@neinwhal Already tried that. Thanks, though.
@Amaz1 I'm using version 1.1.0. When you say the debug.txt file, you mean the file I made a screenshot of?

**Comment by neinwhal** [comment]
actually. it might be a faulty minetest download. Can you start a normal minetest world with minetest_game, not LOTT.

**Comment by b3u** [comment]
Yep.

**Comment by neinwhal** [comment]
Does the latest version works for you?
https://github.com/minetest-LOTR/Lord-of-the-Test/archive/master.zip

**Comment by b3u** [comment]
No

**Comment by neinwhal** [comment]
Still the same error?

**Comment by b3u** [comment]
Yes. The screenshot was from the master file.

**Comment by neinwhal** [comment]
Can you try a fresh download of minetest?
I am not able to recreate the error, so I dont think its coming from LOTT's side.

**Comment by b3u** [comment]
Thanks, works now.
