### ISSUE TITLE
Improved Website

### ISSUE THREAD

**Issue by b3u** [minetest-LOTR/Lord-of-the-Test#133]
I saw the game's website, and I liked it. I know HTML, CSS and graphic design, and I think I can help with the website.

Here's what I'd like to work on:
1. Expanded Contact section
2. Expanded About section
3. Support for small screen sizes.
4. Stylistic fix to navbar
5. A link to the Minetest website somewhere on the site.

**Comment by Amaz1** [comment]
If you're still up for working on it, you're more than welcome to! All of those improvements would be very much appreciated!
The repo for the website is here: https://github.com/minetest-LOTR/minetest-LOTR.github.io

**Comment by b3u** [comment]
Thanks, I'd love to. I've already forked it. Could you explain the file system to me? I'm still learning the Github, and I haven't used Jekyll or Ruby before. I'm also having trouble previewing my changes correctly. It doesn't integrate the CSS for me.

**Comment by Amaz1** [comment]
Nope, no need at all :) They were just from the basic github template.

**Comment by b3u** [comment]
So, I'm basically finished with the website. All that's missing is contact info for Amaz1, neinwahl and lumidify. I can open a pull request now and let you fill it in, or wait.
