### ISSUE TITLE
Server crashes with async error related to lottfarming

### ISSUE THREAD

**Issue by RGAM496** [minetest-LOTR/Lord-of-the-Test#136]
I have started a new dedicated server in a headless Ubuntu Server 18.04 LTS. I have just installed the game with `apt install minetest-server`, and then I have cloned the repository in games. After that, I have created a world in a GUI client on other computer, and copied the files via SSH.

When I was playing, I have tried to pick a cabbage with another one on my hand, and the server has been crashed (I have tried to replicated it, and it happened once more).

The log data is:
```
ACTION[Server]: RGAM uses lottfarming:cabbage, pointing at
 [object 130]
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua:
 Runtime error from mod 'lottfarming' in callback item_OnUse(): ...r/.minetest/games/Lord-of-the-Test/mods/stamina/init.
lua:261: attempt to index a nil value
ERROR[Main]: stack traceback:
ERROR[Main]:         ...r/.minetest/games/Lord-of-the-Test
/mods/stamina/init.lua:261: in function <...r/.minetest/games/Lord-of-the-Test/mods/stamina/init.lua:259>
minetest-lott.service: Main process exited, code=exited, status=1/FAILURE
minetest-lott.service: Failed with result 'exit-code'.
```

If that error is related to a bug (and not a missconfiguration), I guess it should be of help.

**Comment by neinwhal** [comment]
Sorry for the late response.
I'm not too sure how you managed to accomplish the mentioned act;
Because cabbage is considered a food, punching something with it will cause you to eat it which overrides the punching action entirely.

Following that logic, are you able to replicate the bug with having another food in hand and punching any crop/block?

**Comment by Amaz1** [comment]
Had to do with enable damage being enabled.
Fixed.
