### ISSUE TITLE
crashes with attempt to call method 'get_2d' (a nil value)

### ISSUE THREAD

**Issue by FinishedFragment** [minetest-LOTR/Lord-of-the-Test#139]
While using the latest version on master I encountered some crashes while roaming the world (generated with Mapgen v7):

```
ERROR[Main]: ServerError: AsyncErr: Lua: finishGenRuntime error from mod 'flowers' in callback environment_OnGenerated(): ....minetest/games/Lord-of-the-Test/mods/flowers/mapgen.lua:15: attempt to call method 'get_2d' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	....minetest/games/Lord-of-the-Test/mods/flowers/mapgen.lua:15: in function <....minetest/games/Lord-of-the-Test/mods/flowers/mapgen.lua:1>
ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:420: in function </usr/share/minetest/builtin/game/register.lua:400>
```

and a similar one which happens more often:

```
ERROR[Main]: ServerError: AsyncErr: Lua: finishGenRuntime error from mod 'lottmapgen' in callback environment_OnGenerated(): ...minetest/games/Lord-of-the-Test/mods/lottmapgen/init.lua:184: attempt to call method 'get_2d_map_flat' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	...minetest/games/Lord-of-the-Test/mods/lottmapgen/init.lua:184: in function <...minetest/games/Lord-of-the-Test/mods/lottmapgen/init.lua:110>
ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:420: in function </usr/share/minetest/builtin/game/register.lua:400>
```

Minetest version 0.4.17.1

**Comment by FinishedFragment** [comment]
If a singlenode world is generated, the subgame will crash instantly with one of the above errors (seems random to me). I tested this with a few, freshly generated worlds.
Also, in a 'normal' world (mapgen v7) being near or entering a angmar biome causes more crashes in my case.

**Comment by peternowee** [comment]
Same here, also on Minetest 0.4.17.1. On entering newly generated worlds, the character selection dialog briefly shows up, but then the entire screen turns grey and Minetest becomes unresponsive.

I checked with previous commits and found the problem to be caused by the most recent commit: 2e376bd, PR #134, which replaced some deprecated functions in preparation for Minetest v5. The error messages also mention the new function names (`get_2d` and `get_2d_map_flat`) introduced by that commit.

**Comment by FinishedFragment** [comment]
Can confirm, can't generate new worlds with LOTT, just tested it

**Comment by neinwhal** [comment]
get_2d and get_2d_map_flat are functions that only work in Minetest-0.5.0-dev, so it will crash in any older versions.
But that isn't suppose to be the case, this master branch is suppose to still remain compatible for older minetest versions, I'll revert any 0.5.0-dev specific changes.

**Comment by Amaz1** [comment]
Minetest 5.0.0 has been released, so I guess this is invalid now. Let me know if I need to actually do anything with LOTT to fix it, but 0.4.16/17 are no longer supported!

**Comment by FinishedFragment** [comment]
@Amaz1 tested with Minetest 5.0.0. Still happens:

```
ServerError: AsyncErr: Lua: finishGenRuntime error from mod 'lottmapgen' in callback environment_OnGenerated(): ...minetest/games/Lord-of-the-Test/mods/lottmapgen/functions.lua:941: attempt to compare nil with numbe
stack traceback:
	...minetest/games/Lord-of-the-Test/mods/lottmapgen/functions.lua:941: in function 'lottmapgen_biomes'
	...minetest/games/Lord-of-the-Test/mods/lottmapgen/init.lua:222: in function <...minetest/games/Lord-of-the-Test/mods/lottmapgen/init.lua:110>
	/usr/share/minetest/builtin/game/register.lua:419: in function </usr/share/minetest/builtin/game/register.lua:399>
```

**Comment by Amaz1** [comment]
@FinishedFragment I think that is to do with the issue you describe in #140, not the get_2d etc., as that should all work in MT 5.0.0, and the error you just posted is more akin to the one found in the other issue, rather than the ones you posted here.
