### ISSUE TITLE
visual player character 'glitching' through all blocks

### ISSUE THREAD

**Issue by FinishedFragment** [minetest-LOTR/Lord-of-the-Test#145]
The player's perspective:
![viewport](https://user-images.githubusercontent.com/44732327/55647524-6707fe00-57cd-11e9-96f9-ea0590b09f1a.png)

And how it looks from the outside:
![external](https://user-images.githubusercontent.com/44732327/55647523-6707fe00-57cd-11e9-8e47-71e0900d0ac2.png)

**Comment by LoneWolfHT** [comment]
Have to move the player upwards with blender. `G + Z + '10'` once you've selected everything should fix it. If I haven't forgotten something

**Comment by Amaz1** [comment]
https://github.com/minetest-LOTR/Lord-of-the-Test/commit/b2859572031bd6d2486587eccf65fb4a4043d169
