### ISSUE TITLE
Papyrus doesn't grow (Patch suggestion)

### ISSUE THREAD

**Issue by micmul** [minetest-LOTR/Lord-of-the-Test#150]
Papyrus does not grow on other substrates (i.e. the cube papyrus is supposed to grow on) than raw dirt. Since dirt turns into grass after a short time this hampers papyrus production.

Apparently the substrate is not referenced properly in ~/.minetest/games/Lord-of-the-Test/mods/default/functions.lua. The following patch works for me:
```

256c256
< 	neighbors = {"default:dirt", "default:dirt_with_grass"},
---
> 	neighbors = {"default:dirt", "lottmapgen:default_grass"},
262c262
< 		if name == "default:dirt" or name == "default:dirt_with_grass" then
---
> 		if name == "default:dirt" or name == "lottmapgen:default_grass" then
```

**Comment by Amaz1** [comment]
Papyrus grows for me on sand, dirt, and dirt with any grass... Also, those lines don't seem to match with the current lines in functions.lua. The current code is as follows:
```lua
nodenames = {"default:papyrus"},
neighbors = {"group:soil", "group:sand"},
```
and
```lua
if minetest.get_item_group(name, "soil") ~= 0
or minetest.get_item_group(name, "sand") ~= 0 then
```
So I'm not quite sure what's going on here.

**Comment by Amaz1** [comment]
Retested this in the latest commit, seems that papyrus grows fine.
Closing, but if you can reproduce this, let me know.
