### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by amunizp** [minetest-LOTR/Lord-of-the-Test#155]
`ModError: Failed to load and run script from /home/owlgirl/.minetest/games/Lord-of-the-Test-1.1.0/mods/mobs/init.lua:
Unknown node: default:obsidianbrick
stack traceback:
	[C]: in function 'get_content_id'
	....minetest/games/Lord-of-the-Test-1.1.0/mods/mobs/api.lua:2521: in main chunk
	[C]: in function 'dofile'
	...minetest/games/Lord-of-the-Test-1.1.0/mods/mobs/init.lua:3: in main chunk
Check debug.txt for details.`

Content of debug.txt

> 

> 
> 
> -------------
>   Separator
> -------------
> 
> 2020-05-27 15:07:31: WARNING[Main]: Undeclared global variable "invisibility" accessed at ....minetest/games/Lord-of-the-Test-1.1.0/mods/mobs/api.lua:46
> 2020-05-27 15:07:31: ERROR[Main]: ModError: Failed to load and run script from /home/owlgirl/.minetest/games/Lord-of-the-Test-1.1.0/mods/mobs/init.lua:
> 2020-05-27 15:07:31: ERROR[Main]: Unknown node: default:obsidianbrick
> 2020-05-27 15:07:31: ERROR[Main]: stack traceback:
> 2020-05-27 15:07:31: ERROR[Main]: 	[C]: in function 'get_content_id'
> 2020-05-27 15:07:31: ERROR[Main]: 	....minetest/games/Lord-of-the-Test-1.1.0/mods/mobs/api.lua:2521: in main chunk
> 2020-05-27 15:07:31: ERROR[Main]: 	[C]: in function 'dofile'
> 2020-05-27 15:07:31: ERROR[Main]: 	...minetest/games/Lord-of-the-Test-1.1.0/mods/mobs/init.lua:3: in main chunk
> 2020-05-27 15:07:31: ERROR[Main]: Check debug.txt for details.
> 2020-05-27 15:07:31: ACTION[Main]: Server: Shutting down

**Comment by Amaz1** [comment]
You have an old version of LOTT. This was fixed a couple of days ago: bc5927e86fa0f6e999be2c27c1d274f552bc719d

You need to get v1.2.2: https://github.com/minetest-LOTR/Lord-of-the-Test/releases/tag/v1.2.2
