### ISSUE TITLE
Crash occurs when getting close to an enemy entity

### ISSUE THREAD

**Issue by MCAnimators02** [minetest-LOTR/Lord-of-the-Test#159]
Every time I get close to another entity in the game, a crash occurs and shuts down my game.

information:
OS: Ubuntu(linux) 20.04.1LTS
Minetest version: 5.3 latest/stable

No mods were used during play
![Screenshot from 2020-07-19 22-46-35](https://user-images.githubusercontent.com/68525307/87894854-e694fd00-ca11-11ea-9a3c-d72d9607c45c.png)

**Comment by Amaz1** [comment]
I wasn't able to reproduce this, but I pushed something that should hopefully fix it: https://github.com/minetest-LOTR/Lord-of-the-Test/commit/8742df24bffe12dec0571047ee916093122844fb

Would you be able to test that commit and see if it fixes the crash? Thanks!

**Comment by hecktest** [comment]
`bad argument #1 to 'type' (value expected)`

How about: `if not (self.object and self.object:get_pos()) then return; end`

**Comment by hecktest** [comment]
But after that is fixed, this happens:
`mobs/api.lua:205: attempt to index local 'b' (a nil value)`
The actual trouble is in:
https://github.com/minetest-LOTR/Lord-of-the-Test/blob/8742df24bffe12dec0571047ee916093122844fb/mods/mobs/api.lua#L2028

You have to patch this check into every place where you use the position of a potentially deleted object.

**Comment by Amaz1** [comment]
Are there any further crashes after https://github.com/minetest-LOTR/Lord-of-the-Test/commit/16761d597b37555634cfc60b3c6583592fdadb21?
I updated the mobs api again.

**Comment by hecktest** [comment]
Doesn't crash any more, but my bow stopped working.

**Comment by Amaz1** [comment]
Ah, excellent!
@MCAnimators02 would you mind confirming if this solves your problem or not?

**Comment by hecktest** [comment]
Just a hint; instead of validating every time get_pos or another property is needed, it would be more optimal to track down all entry points for entity code and bail out early there.

**Comment by Amaz1** [comment]
I just copied the code from the latest commit of mobs api (https://notabug.org/TenPlus1/mobs_redo). Making large changes like that would make updating the api even harder, so unless that's done in tenplus1's repo, I'll stay away from doing that.
Also, I don't have the time or interest to track down every entry point :P

**Comment by Amaz1** [comment]
Seems to be fixed...
If this reoccurs, this can be reopened/a new issue can be opened.
