### ISSUE TITLE
Chairs in a 2 node high area can trap you

### ISSUE THREAD

**Issue by hecktest** [minetest-LOTR/Lord-of-the-Test#161]
This is a chair node in a random Gondor fort.
![chairs](https://user-images.githubusercontent.com/42101236/88074778-2544c780-cb78-11ea-8ef7-06e597b09e05.png)
The room this is generated in is only 2 nodes high, so you do not have enough space to get out of the chair once you right click it. After using one, you are quite stuck, only able to hop between chairs in range.

**Comment by Amaz1** [comment]
Still is possible to get trapped, but it's a lot harder now, as the chair would have to be surrounded on all sides, which, imo, is acceptable, as there are other ways to get trapped in LOTT or Minetest in general (e.g. falling into a cave without a pick).
