### ISSUE TITLE
Mutually hostile NPCs glitch out when in the same XZ position but on a different Y level.

### ISSUE THREAD

**Issue by hecktest** [minetest-LOTR/Lord-of-the-Test#163]
![pathing](https://user-images.githubusercontent.com/42101236/88468239-de8cff80-cee0-11ea-85c6-c027d923abd0.gif)
Solution: do proper pathing

**Comment by Amaz1** [comment]
This is a problem with the mobs api, and as I said, I don't want to make any major changes in the mobs api. So unless it's fixed upstream, it probably won't be fixed in LOTT.

It's certainly something to consider for the mobs api in the rewrite branch.

**Comment by neinwhal** [comment]
Closing this since LOTT has discontinued development, and a rewriting or reimplementation of the mob API in LOTT is too much work than it's worth now. Hopefully, Third Age will have better systems to prevent this.
