### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by totallyanorc** [minetest-LOTR/Lord-of-the-Test#164]
This keeps showing up:

AsyncErr: ServerThread::run Lua: Runtime error from mod 'lottmobs' in callback luaentity_Step(): ...est/1619/.minetest/games/lordofthetest/mods/mobs/api.lua:205: attempt to index local 'b' (a nil value)
stack traceback:
	...est/1619/.minetest/games/lordofthetest/mods/mobs/api.lua:205: in function 'get_distance'
	...est/1619/.minetest/games/lordofthetest/mods/mobs/api.lua:2033: in function 'follow_flop'
	...minetest/games/lordofthetest/mods/lottmobs/functions.lua:297: in function 'do_custom'
	...est/1619/.minetest/games/lordofthetest/mods/mobs/api.lua:3417: in function <...est/1619/.minetest/games/lordofthetest/mods/mobs/api.lua:3295>

The game closes every time I get this error.

**Comment by Amaz1** [comment]
Are you using the latest version of Lord of the Test? There have been fixes related to that pushed recently.

If you could see if it still happens when using the latest commit (2572301) and let me know, that would be great!

**Comment by totallyanorc** [comment]
I don't know, I'm using the version I got from Minetest's "Install games from ContentDB" thing.

**Comment by Amaz1** [comment]
Ah, okay.
That isn't the latest version. I will make a release there later today/tomorrow.

**Comment by Amaz1** [comment]
Should be fixed in this: https://github.com/minetest-LOTR/Lord-of-the-Test/releases/tag/v1.2.3
Updated the contentDB as well, so if you could update your game and let me know, that would be great.

(And yes, that was a **little** latter than "later today/tomorrow"!!

**Comment by totallyanorc** [comment]
I updated it from contentdb.
Why are 99% of the items and all the mobs gone and why is the same biome everywhere?

Also, bugs:

https://i.imgur.com/bfRtjxl.png
https://i.imgur.com/eHwRDD4.png

**Comment by Amaz1** [comment]
Opps, the release was based on the wrong branch...
Try this: https://github.com/minetest-LOTR/Lord-of-the-Test/releases/tag/v1.2.4
It should work, and the contentdb is updated.
Sorry about that.

**Comment by totallyanorc** [comment]
Everything is working now.

https://i.imgur.com/bBPmvJS.png

**Comment by Amaz1** [comment]
Great!
Lots of fire there!!
