### ISSUE TITLE
Problem with hot ringsilver on LOTT v.1.2.1

### ISSUE THREAD

**Issue by george-andr** [minetest-LOTR/Lord-of-the-Test#165]
Hi I am using minetest server v 5.1.1 compiled from source code. Our server runs on Debian 10.

The main problem: when I try to drop hot ringsilver in water to cool it down, as mentioned in the ring handbook, it stays for a few seconds and then disappears.

Is this a bug or should it behave like that?
Do you have any idea why this happens.

**Comment by lumidify** [comment]
Hi,
I know it's been over 3 months, but in case you haven't figured it out yet:
1. The hot ring silver has to be dropped into an actual water source, not just flowing water.
2. You have to drop the hot ring silver into the water quickly after it is produced by the furnace (within 13 seconds).
If either of these are not the case, it will just disappear as you were experiencing.
Sorry that I didn't answer sooner.

**Comment by george-andr** [comment]
Thanks, I now realize that it wasn't within the 13 seconds.
