### ISSUE TITLE
Missing textures warnings and missing screenshots for race selection

### ISSUE THREAD

**Issue by FinishedFragment** [minetest-LOTR/Lord-of-the-Test#168]
**This is a non-fatal bug**.

There are many repeated Irrlicht-related warnings about missing textures at startup:

```
WARNING[Main]: Irrlicht: Could not open file of texture: 2_TEXTURE_ARMOUR.png 
WARNING[Main]: Irrlicht: Could not open file of texture: 1_TEXTURE_BODY.png
WARNING[Main]: Irrlicht: Could not open file of texture: 4_TEXTURE_WIELD_RIGHT.png
WARNING[Main]: Irrlicht: Could not open file of texture: 5_TEXTURE_WIELDLEFT.png
WARNING[Main]: Irrlicht: Could not open file of texture: 3_TEXTURE_CAPE.png
WARNING[Main]: Irrlicht: Could not open file of texture: 6_TEXTURE_SHIELD.png 
WARNING[Main]: Irrlicht: Could not open file of texture: 7_BAG.png
```

The following races do not have screenshots (or texts, but this is only semi-relevant):

- Mordor Orc
- Angmar Orc
- Misty Mountains Orc
- Rohan Human
- Gondor Human

When trying to select one of these races, there will be a non-fatal error:

```
ERROR[Main]: generateImage(): Could not load image "lottplayer_man_gondor_screenshot.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "lottplayer_man_rohan_screenshot.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "lottplayer_orc_angmar_screenshot.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "lottplayer_orc_misty_mountains_screenshot.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "lottplayer_orc_mordor_screenshot.png" while building texture; Creating a dummy image
```

[missingfiles.log](https://github.com/minetest-LOTR/Lord-of-the-Test/files/5674448/missingfiles.log)

**Comment by lumidify** [comment]
Hi,
I'm assuming you're using the v2-rewrite branch (which is the default in the repository). This is very experimental at the moment, as the readme says, so it's expected that a lot of things will be broken. Sadly no one currently has time to work on it, so it's very likely that it will stay like that for a while. Thanks for reporting it though - I'll leave the issue open so we have a list of things that are broken when someone decides to keep working on it.

**Comment by Amaz1** [comment]
In terms of the first part, the missing textures, I discussed it with @neinwhal, and he's not sure of how to fix 
> <neinwhal> frankly i have no idea how to fix that
> <neinwhal> even adding an texture of that name doesnt fix it
> <neinwhal> its an issue for the armour model also
> <neinwhal> iirc i spent like a week trying to fix that with no avail 
If you have any experience with blender/modeling, you're more than welcome to have a go at fixing it... But it's not too serious, as it's just a warning, just a little bit annoying...

I'll push a commit for the second half in a minute or two.
