### ISSUE TITLE
Leaf Z-fighting

### ISSUE THREAD

**Issue by FinishedFragment** [minetest-LOTR/Lord-of-the-Test#170]
In both master and the latest v2-rewrite branch there is Z-fighting occurring on basically every leaf-material.

![z-fighting](https://user-images.githubusercontent.com/44732327/102945557-57a77780-44be-11eb-99c4-ece7824f0559.png)

It might be caused by overlapping faces in the model. The effect is even more visible when enabling waving leaves.

Steps to reproduce:
- Optional: enable waving leaves
- Roam the world until you find a tree
- The Z-fighting will become visible if you move around the tree a bit or just climb of it

**Comment by lumidify** [comment]
This is caused by the setting `visual_scale` in the node definitions for the leaves. Currently, it seems to be set to `1.3`, meaning that the leaves overlap a bit. When I change `visual_scale` to `1.0`, the problem isn't there anymore and I can't see any drawbacks, but I'm a bit confused as to why it was done that way in the first place. Maybe it was meant to be like that as a special effect (although that would seem a bit weird).

**Comment by Amaz1** [comment]
Are you sure this is a problem in the v2-rewrite branch? I can't reproduce it there (and the visual scale setting isn't used there...)
Fixed for master (904425a).
I'm not entirely sure why leaves had visual scale set. I think it comes from paragenv7, the base for lottmapgen in master, which set them like that. I think (I can't quite remember now) that the leaves there were plantlike, and for plantlike leaves, it looks better if they're slightly bigger (more bushy). However, I dislike plantlike leaves, so I changed them back to allfaces_optional. But I use simple leaves, and visual scale doesn't affect them, so I never noticed that there was a problem here!

**Comment by FinishedFragment** [comment]
I just tested it and its fixed in master.

I also tested the v2-rewrite branch and it looks alright but the leaves are not waving. I might have been mistaken about the Z-fighting in v2-rewrite but there certainly is none after pulling the latest commits. Thanks for the fix!

**Comment by Amaz1** [comment]
Excellent! Thank you for testing.
I'll add the flag for leaves waving and push that in a bit.
