### ISSUE TITLE
Damage still applies in creative mode

### ISSUE THREAD

**Issue by FinishedFragment** [minetest-LOTR/Lord-of-the-Test#171]
Although there is no health bar, the player can still be damaged in creative mode **even when enable damage is off**.

Steps to reproduce:

- Join or create a world and make sure to check creative mode and to uncheck enable damage.
- Take damage and die

I tested the following things and all will kill the player in creative mode:
- Falling damage
- Drowning (there is no bar indicating your breath but you will still drown)
- Swimming in lava
- Swimming in mordor water

**Comment by lumidify** [comment]
This should be fixed now in the master branch. Could you please test it again and report if it works?

**Comment by lumidify** [comment]
...and now it should also be fixed in v2-rewrite.

**Comment by FinishedFragment** [comment]
Can confirm that its fixed now.

Thanks for the quick fix! Awesome work :+1:
