### ISSUE TITLE
lottores: Failed to load and run script

### ISSUE THREAD

**Issue by isAAAc** [minetest-LOTR/Lord-of-the-Test#178]
hello, 
(installed via the .zip , i tried a git clone too

* fresh install on a **`debian 11.3`**
```bash
minetest-server                      5.3.0+repack-2.1+deb11u1       amd64

/var/games/minetest-server/.minetest/games# dpkg -l |grep lua
ii  libluajit-5.1-2:amd64                2.1.0~beta3+dfsg-5.3           amd64
ii  libluajit-5.1-common                 2.1.0~beta3+dfsg-5.3           all
ii  lua-bitop:amd64                      1.0.2-5                        amd64
ii  lua-socket:amd64                     3.0~rc1+git+ac3201d-4          amd64
```
* install path: `/var/games/minetest-server/.minetest/games/Lord-of-the-Test-1.1.0`
* log output when starting the service via `systemctl start minetest-server`:
https://krashboyz.org/zerobin/?5b9e79f7c7795859#H1hVPVgS6AwbpxohzA1J7TDPJ8RG474TjiaaBWBRQKj

could someone help me please ? (tell me if you need more information)
(edit: add lua versions in system)

**Comment by isAAAc** [comment]
same issue in bookworm debian: 
```
ii  minetest-server                      5.4.1+repack-2+b1

ii  libluajit-5.1-2:amd64                2.1.0~beta3+dfsg-6                amd64        Just in time compiler for Lua - library version
ii  libluajit-5.1-common                 2.1.0~beta3+dfsg-6                all          Just in time compiler for Lua - common files
```

**Comment by BuckarooBanzay** [comment]
(discussed in irc, but here again)
The problem is in the "sound" field here:
https://github.com/minetest-LOTR/Lord-of-the-Test/blob/a32efbd6fb13cb10e2700373f57b68e22ac7a8de/mods/lottores/init.lua#L93

**Comment by isAAAc** [comment]
Lord-of-the-Test-1.1.0  yes, i believed it was the last version , i'll try with a fresh one then , thx for your answer, 
i'll give a feedback after testing

**Comment by neinwhal** [comment]
If you can provide a debug file from minetest that would be more useful too.
There should be a debug.txt within your minetest directory.
Once minetest crash, open that file and copy the last few lines.

**Comment by isAAAc** [comment]
i was with https://github.com/minetest-LOTR/Lord-of-the-Test/archive/v1.1.0.zip

it works perfectly with https://github.com/minetest-LOTR/Lord-of-the-Test/releases/tag/v1.2.5

thx for your help on irc libera #lordofthetest

i close this issue

**Comment by neinwhal** [comment]
This issue brought up BuckarooBanzay has already been fixed on the master version a few years ago;
https://github.com/minetest-LOTR/Lord-of-the-Test/commit/bc5927e86fa0f6e999be2c27c1d274f552bc719d

Are you using a version that is older than that?
