### ISSUE TITLE
`Stamina` mod issue

### ISSUE THREAD

**Issue by MoNTE48** [minetest-LOTR/Lord-of-the-Test#180]
```lua
ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'lottfarming' in callback item_OnUse():
.../files/games/lordofthetest/mods/stamina/init.lua:73: attempt to index a nil value stack traceback:
.../files/games/lordofthetest/mods/stamina/init.lua:73: in function 'change'
.../games/lordofthetest/mods/lottfarming/orc_food.lua:8: in function
<.../files/games/lordofthetest/mods/lottfarming/orc_food.lua:4>
```

I can highly recommend updating the [Stamina mod](https://github.com/minetest-mods/stamina) to support the latest versions of Minetest Engine. Or at least add a nil check at the place of this crash.

**Comment by MoNTE48** [comment]
@neinwhal, any chance you can look at this problem?

**Comment by neinwhal** [comment]
Not able to fully reproduce said error, can you clarify what triggers it?

**Comment by MoNTE48** [comment]
@luk3yx, maybe you remember what the problem was?
Calling this function when the player is already leave, or the player is nil in the join function?

**Comment by luk3yx** [comment]
I haven't tested it myself but it looks like eating Orc food with `enable_damage = false` could trigger the crash.

**Comment by neinwhal** [comment]
Applied sort of a bandaid to the situation; 82c72f9657da55fd72832c895f8691f2fe8550d0
Stamina isn't enabled when damage isn't enabled for some reason, therefore causing the crash when orc food attempts to change stamina when damage is disabled.

I'll need to check with Amaz again the original intention for it and see if there's a need for a more propr fix, but this bandaid should fix the crash at least.
Feel free to reopen if this doesn't resolve the issue.
