### ISSUE TITLE
Mordor waters should be opaque inside as well

### ISSUE THREAD

**Issue by xeruf** [minetest-LOTR/Lord-of-the-Test#184]
yeah....

![screenshot_20221230_000629](https://user-images.githubusercontent.com/13354331/210021278-eef15cfc-0de4-42a8-8d67-ba0554aeb377.png)
![screenshot_20221230_000633](https://user-images.githubusercontent.com/13354331/210021287-b5e8dcf6-9d5a-4adb-9fc0-4aa0202701a0.png)

it should look muddy from the inside and the side. And this transition in the middle of the lake is also a little jarring. Maybe you can fix worldgen to never put water across biomes?

**Comment by neinwhal** [comment]
the see-through is a minetest engine issue, which afaik, hasn't been fixed.
i.e. in MTG disable lavacooling and place water & lava next to each other, you get the same issue.

There is no good way to detect how big a body of water and the extend of its limits, so doing that via worldgen is not a feasible approach either. The best and only way I can think of currently is to implement a transitional blend.

That being said, with Third Age, we will have more control of the map generation, and hopefully a method can be done to prevent it there. But in LOTT, both of these issues aren't fixable.

Feel free to reopen if you have additional suggestions or examples of some existing functionable methods.
