### ISSUE TITLE
Don't grow fruits (plums) on trunks

### ISSUE THREAD

**Issue by xeruf** [minetest-LOTR/Lord-of-the-Test#185]
lol

![screenshot_20221229_234148](https://user-images.githubusercontent.com/13354331/210021649-915ddd4b-529a-4066-9cf4-0ceb5f8001d4.png)

**Comment by neinwhal** [comment]
https://github.com/minetest-LOTR/Lord-of-the-Test/commit/32eab389274593f91f7f1625d6846bc5f43143e7
