### ISSUE TITLE
License clarification needed in lottplants.

### ISSUE THREAD

**Issue by pithydon** [minetest-LOTR/Lord-of-the-Test#57]
Textures are licensed under CC BY-SA, but what version?

**Comment by Amaz1** [comment]
All textures are CC BY-SA 3.0, unless otherwise stated. I'll add this info to the license.txt files when I get a chance.

**Comment by Amaz1** [comment]
https://github.com/minetest-LOTR/Lord-of-the-Test/commit/833ada5ee4960919af70f8b04696b00c9f491a5c
