### ISSUE TITLE
Many missing texture erros when equipping armor

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-LOTR/Lord-of-the-Test#79]
In LOTT 1.0.0 in Minetest 0.4.14, LOTT has very often missing texture errors just by equipping or unequipping some armor.

**Comment by Amaz1** [comment]
Fixed by https://github.com/minetest-LOTR/Lord-of-the-Test/commit/924c6bd8aef04b1c4f7b573295b4969285b6bc7e
