### ISSUE TITLE
Suggestion: Remove or replace mese

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-LOTR/Lord-of-the-Test#81]
I think this should be really a no-brainer.
Mese is really out of place in this game because it is an invention of celeron55 and not Tolkien.

My first suggestion would be to remove mese but I fear this would probably mess up gameplay and compability too much. So the better idea would be just to replace mese by something else.
Technically, this could be baby simple in theory. Just by renaming all the relevant items and nodes and maybe drawing some different textures and that's basically it. I would not change the internal itemstrings, however, to not mess with compability.

Sorry, I have no real idea of what item/mineral/whatever could be used in place of mese. So I guess finding a good replacement thing is the “hard” part. xD

**Comment by fishyWET** [comment]
This "issue"/"question" have been brought out multiple times.
Amaz and I have previously discussed about this.
Our conclusion was to keep Mese.

> Mese is really out of place in this game because it is an invention of celeron55

This is exactly why Mese is unique, something much like diamond is the branding for Minecraft, Mese is the branding of Minetest.
To remove it would just remove the identity of Minetest.
So it's a "wontfix".

**Comment by Amaz1** [comment]
This has been open for a month, and no new discussion has taken place since it was first opened. I think that "a bit" of time has passed, and that it can now be closed :)
Feel free to comment still though!
