### ISSUE TITLE
Selection boxes need improvement

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-LOTR/Lord-of-the-Test#86]
The selection boxes of some items, especially plants, need more love IMO.

In many cases they don't really match the shape of the plant, so they should be tweaked.
The worst offender here is the melon node, this should be the first selection box to be improved. You can actually point through the melon unless you point to the middle of it. Which makes it annoying to dig melons.
The other plants are not that important.

**Comment by Amaz1** [comment]
I fixed the melons and cabbages a while ago. https://github.com/minetest-LOTR/Lord-of-the-Test/commit/134de846616eb6952e0bf4d858e516b3b746f729

Other things do still need some work doing to them though

**Comment by Amaz1** [comment]
I think that this commit makes all of the plant selection boxes more or less acceptable now.
