### ISSUE TITLE
Chests in wooden fortress contains unknown items

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-LOTR/Lord-of-the-Test#87]
As of LOTT 1.0.0, the chests in wooden fortresses sometimes contain unknown items.

**Comment by Amaz1** [comment]
Fixed by https://github.com/minetest-LOTR/Lord-of-the-Test/commit/eb6c877b75652a18644a359ab4125e1864a0dddc

(I should make another release of LOTT, but that requires Minetest to have another release, as LOTT uses dev version only features.)
