### ISSUE TITLE
Tin stair and tin slabs can't be crafted, tin blocks produce galvorn stair/slab instead

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-LOTR/Lord-of-the-Test#88]
In LOTT 1.0.0, if you put the tin blocks in this shape (T=tin block, X=nothing) into the craft grid:

    TXX
    TTX
    TTT

or

    XXT
    XTT
    TTT

You don't get tin stairs, but galvorn stairs! :D 

If you use this shape:

    TTT

You get galvorn slabs!

**Comment by Amaz1** [comment]
This was fixed by https://github.com/minetest-LOTR/Lord-of-the-Test/commit/5c8964776515cddcb98e3dcd442eba0ddb404124
