### ISSUE TITLE
A few item names/descriptions are poor/incomplete/missing

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-LOTR/Lord-of-the-Test#89]
LOTT has a few items with a poor item name (`description` field / tooltip). Please rename these items accordingly:

* Chairs and tables have missing space, like “AlderChair”, “BirchChair”, “JunglewoodTable”, …
* Potion and potion arrow names are somewhat cryptic like “Atheltas Brew (Strength: corruption1)”. Either remove the paranthesis altogether or use a word which is understandable
* These slab and stair names look very technical:
    * dwarfstone_black
    * dwarfstone_white
    * leafroof_dark
    * leafroof_mallorn
    * mallorn_pillar
    * mallorn_white
    * tree_mossy
    * tree_vine

**Comment by Amaz1** [comment]
Fixed https://github.com/minetest-LOTR/Lord-of-the-Test/commit/2df13329ff1a8234d26e30cf98356363c1abc791

For potions, the "strength" has been moved onto a line of its own:
![screenshot_20161111_122039](https://cloud.githubusercontent.com/assets/4390945/20215043/b9dc42a6-a809-11e6-8c46-31ec4cd99c31.png)
I don't know if this is the best way of proceeding, but I couldn't think of any better way. If you have a better suggestion, please make it!

**Comment by Wuzzy2** [comment]
Oh, you can use newlines in descriptions? Nice!
I think this solution will work for now but I am pretty sure Minetest's item tooltips have to be completely reworked in the future. But your solution is perfectly OK for now.
