### ISSUE TITLE
This is a test

### ISSUE THREAD

**Issue by lumidify** [minetest-LOTR/Lord-of-the-Test#93]
This is a test.
As such, this is not a real issue.
Please do not think that this is a real issue because it's not.

FAQ:
Q: Is this a real issue?
A: No.
Q: Why is this not a real issue?
A: Because I want to annoy you.
Q: But...
A: Live with it.
Q: Is LOTT any good?
A: Yes.
Q: Are roses red?
A: It depends.
Q:
A: Shut up.

**Comment by Amaz1** [comment]
(Some clarification: @lumidify and I are testing an IRC bot for #lordofthetest on Freenode :P)
