### ISSUE TITLE
ringsilver furnace can't be put

### ISSUE THREAD

**Issue by koma78** [minetest-LOTR/Lord-of-the-Test#97]
am not able to put the ringsilver furnace (the one made out of the original furnace). trying to put it in the middle of 3*3 square of lava, but it says the area isn't hot enough. is there anything else to consider?
![screenshot - 03042017 - 09 21 00 am](https://cloud.githubusercontent.com/assets/26186502/23579857/e9791e3e-00bb-11e7-9452-77e4e272e80d.png)

**Comment by fishyWET** [comment]
It must be 9 lava **source** blocks. (Lava source blocks do not have a "flowing" animation)
Place the ringsilver furnace **above** the lava source blocks (Use a "scaffold" assist in the placement)

**Comment by koma78** [comment]
thanks for the quick reply! still trying to figure that out, i do have 9 lava source blocks there (they wave a little, but do not flow) and am above trying to put that furnace, the very moment i do so it looks like it's gonna work but then it just doesn't and it keeps saying that the area isn't hot enough. something is missing, probably something small and stupid, but i don't get to it.
![screenshot - 03042017 - 10 34 53 am](https://cloud.githubusercontent.com/assets/26186502/23580365/faa4ab38-00c5-11e7-8966-fb9aa9e9e5c5.png)

**Comment by fishyWET** [comment]
It appears the furnace is one block above the lava from the picture(?)
It should be directly above, the bottom of the furnace touching the top the lava source.

**Comment by Amaz1** [comment]
As fishy said, the Ring Furnace needs to go directly above the lava. I've changed the ring guide book to make this clear: https://github.com/minetest-LOTR/Lord-of-the-Test/commit/3d58bbf5cd1d6d05ba1087c0187b481faa4d0aa8

If you have any more questions, let us know!

**Comment by celofyr** [comment]
I have the same issue with minetest 0.4.16
In debug mode, with a bucket selected, I can point at a lavasource (cf screenshot), but if I select the ringsilver furnace, I can not point at a lavasource (no black square around the lavasource, no "pointing_at" in the debug screen)

Bucket screenshot:
![bucket](https://user-images.githubusercontent.com/32101813/30597717-20e6db8e-9d58-11e7-9ea0-c56ed0ba6f9a.png)

Ringsilver furnace screenshot:
![ringsilver_furnace](https://user-images.githubusercontent.com/32101813/30597732-28aa3d7a-9d58-11e7-9154-a0fe3edac3a5.png)

**Comment by celofyr** [comment]
ok sorry, got it ;-)
Need to use a scaffolder...
